# Generated by Django 5.2.4 on 2025-07-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_status_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('jazz_cash', 'Jazz Cash'), ('easy_paisa', 'Easy Paisa'), ('bank_transfer', 'Bank Transfer')], max_length=50),
        ),
    ]
