# Generated by Django 5.2.4 on 2025-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fabric', 'Fabric'), ('bukram', 'Bukram'), ('thread', 'Thread'), ('buttons', 'Buttons'), ('collar', 'Collar'), ('pent', 'Pent'), ('shirt', 'Shirt'), ('monogram', 'Monogram'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
